global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fx-course-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'fx-catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8002']