input {
  file {
    path => "/usr/share/logstash/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    codec => json
  }
}

filter {
  if [service.name] {
    mutate {
      rename => { "service.name" => "[service][name]" }
    }
  }

  if [log.level] {
    mutate {
      rename => { "log.level" => "[log][level]" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-futurex-default"
    action => "create"
  }

  stdout {
    codec => rubydebug { metadata => false }
  }
}
