spring.application.name=fx-catalog-service
server.port=8002
course.service.url=http://localhost:8001
# OpenTelemetry SDK configuration. Traces are sent to the OpenTelemetry Collector.
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.metrics.exporter=none
otel.logs.exporter=none
otel.traces.exporter=otlp

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}